
r2rpc:
 server:
    defaults:
      transport: tcp
      codecs:
        - json
    endpoints:
      - name: foo
        port: 8083
        responders:
          - bar
          - baz
        requesters:
          - baz
 client:
    endpoints:
      - name: foo
        transport: tcp
        codecs:
          - json
        requesters:
          - bar
          - baz
        responders:
          - baz
logging:
  level:
    com.github.mostroverkhov.r2: DEBUG
